// Code generated by Wire protocol buffer compiler, do not edit.
package com.jeffpdavidson.fantasywear.api.model;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class League extends Message {

  public static final String DEFAULT_ACCOUNT_NAME = "";
  public static final String DEFAULT_LEAGUE_KEY = "";
  public static final String DEFAULT_LEAGUE_NAME = "";

  @ProtoField(tag = 1, type = STRING)
  public final String account_name;

  @ProtoField(tag = 2, type = STRING)
  public final String league_key;

  @ProtoField(tag = 3, type = STRING)
  public final String league_name;

  public League(String account_name, String league_key, String league_name) {
    this.account_name = account_name;
    this.league_key = league_key;
    this.league_name = league_name;
  }

  private League(Builder builder) {
    this(builder.account_name, builder.league_key, builder.league_name);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof League)) return false;
    League o = (League) other;
    return equals(account_name, o.account_name)
        && equals(league_key, o.league_key)
        && equals(league_name, o.league_name);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = account_name != null ? account_name.hashCode() : 0;
      result = result * 37 + (league_key != null ? league_key.hashCode() : 0);
      result = result * 37 + (league_name != null ? league_name.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<League> {

    public String account_name;
    public String league_key;
    public String league_name;

    public Builder() {
    }

    public Builder(League message) {
      super(message);
      if (message == null) return;
      this.account_name = message.account_name;
      this.league_key = message.league_key;
      this.league_name = message.league_name;
    }

    public Builder account_name(String account_name) {
      this.account_name = account_name;
      return this;
    }

    public Builder league_key(String league_key) {
      this.league_key = league_key;
      return this;
    }

    public Builder league_name(String league_name) {
      this.league_name = league_name;
      return this;
    }

    @Override
    public League build() {
      return new League(this);
    }
  }
}
